
// Code generated by stanc v2.28.1
#include <stan/model/model_header.hpp>
namespace clickGraph_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 18> locations_array__ = 
{" (found before start of program)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 7, column 2 to column 39)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 8, column 2 to column 34)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 9, column 2 to column 34)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 12, column 2 to column 36)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 14, column 4 to column 33)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 15, column 4 to column 33)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 16, column 4 to column 52)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 17, column 4 to column 115)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 13, column 17 to line 18, column 3)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 13, column 2 to line 18, column 3)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 2, column 2 to column 8)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 3, column 14 to column 15)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 3, column 2 to column 17)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 4, column 14 to column 15)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 4, column 2 to column 17)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 8, column 31 to column 32)",
 " (in 'benchmarks/clickGraph/clickGraph.stan', line 9, column 31 to column 32)"};



class clickGraph_model final : public model_base_crtp<clickGraph_model> {

 private:
  int N;
  std::vector<int> clicks0;
  std::vector<int> clicks1; 
  
 
 public:
  ~clickGraph_model() { }
  
  inline std::string model_name() const final { return "clickGraph_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.28.1", "stancflags = "};
  }
  
  
  clickGraph_model(stan::io::var_context& context__,
                   unsigned int random_seed__ = 0,
                   std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "clickGraph_model_namespace::clickGraph_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 11;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 11;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 12;
      validate_non_negative_index("clicks0", "N", N);
      current_statement__ = 13;
      context__.validate_dims("data initialization","clicks0","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      clicks0 = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 13;
      clicks0 = context__.vals_i("clicks0");
      current_statement__ = 14;
      validate_non_negative_index("clicks1", "N", N);
      current_statement__ = 15;
      context__.validate_dims("data initialization","clicks1","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      clicks1 = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 15;
      clicks1 = context__.vals_i("clicks1");
      current_statement__ = 16;
      validate_non_negative_index("beta1", "N", N);
      current_statement__ = 17;
      validate_non_negative_index("beta2", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + N + N;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "clickGraph_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ similarityAll;
      similarityAll = DUMMY_VAR__;
      
      current_statement__ = 1;
      similarityAll = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
                        0, 1, lp__);
      std::vector<local_scalar_t__> beta1;
      beta1 = std::vector<local_scalar_t__>(N, DUMMY_VAR__);
      
      current_statement__ = 2;
      beta1 = in__.template read_constrain_lub<std::vector<local_scalar_t__>, jacobian__>(
                0, 1, lp__, N);
      std::vector<local_scalar_t__> beta2;
      beta2 = std::vector<local_scalar_t__>(N, DUMMY_VAR__);
      
      current_statement__ = 3;
      beta2 = in__.template read_constrain_lub<std::vector<local_scalar_t__>, jacobian__>(
                0, 1, lp__, N);
      {
        current_statement__ = 4;
        lp_accum__.add(uniform_lpdf<propto__>(similarityAll, 0.0, 1.0));
        current_statement__ = 10;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 5;
          lp_accum__.add(
            uniform_lpdf<propto__>(rvalue(beta1, "beta1", index_uni(i)), 0.0,
              1.0));
          current_statement__ = 6;
          lp_accum__.add(
            uniform_lpdf<propto__>(rvalue(beta2, "beta2", index_uni(i)), 0.0,
              1.0));
          current_statement__ = 7;
          lp_accum__.add(
            bernoulli_lpmf<false>(rvalue(clicks0, "clicks0", index_uni(i)),
              rvalue(beta1, "beta1", index_uni(i))));
          current_statement__ = 8;
          lp_accum__.add(
            log_mix(similarityAll,
              bernoulli_lpmf<false>(rvalue(clicks1, "clicks1", index_uni(i)),
                rvalue(beta1, "beta1", index_uni(i))),
              bernoulli_lpmf<false>(rvalue(clicks1, "clicks1", index_uni(i)),
                rvalue(beta2, "beta2", index_uni(i)))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "clickGraph_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double similarityAll;
      similarityAll = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      similarityAll = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
                        0, 1, lp__);
      std::vector<double> beta1;
      beta1 = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 2;
      beta1 = in__.template read_constrain_lub<std::vector<local_scalar_t__>, jacobian__>(
                0, 1, lp__, N);
      std::vector<double> beta2;
      beta2 = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 3;
      beta2 = in__.template read_constrain_lub<std::vector<local_scalar_t__>, jacobian__>(
                0, 1, lp__, N);
      out__.write(similarityAll);
      out__.write(beta1);
      out__.write(beta2);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      local_scalar_t__ similarityAll;
      similarityAll = DUMMY_VAR__;
      
      similarityAll = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, similarityAll);
      std::vector<local_scalar_t__> beta1;
      beta1 = std::vector<local_scalar_t__>(N, DUMMY_VAR__);
      
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        beta1[(sym1__ - 1)] = in__.read<local_scalar_t__>();
      }
      out__.write_free_lub(0, 1, beta1);
      std::vector<local_scalar_t__> beta2;
      beta2 = std::vector<local_scalar_t__>(N, DUMMY_VAR__);
      
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        beta2[(sym1__ - 1)] = in__.read<local_scalar_t__>();
      }
      out__.write_free_lub(0, 1, beta2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"similarityAll", "beta1", "beta2"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "similarityAll");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta1" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta2" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "similarityAll");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta1" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta2" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"similarityAll\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta1\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"beta2\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"similarityAll\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta1\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"beta2\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((1 + N) + N);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 0;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((1 + N) + N);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 0;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 3> names__{"similarityAll", "beta1",
      "beta2"};
      const std::array<Eigen::Index, 3> constrain_param_sizes__{1, N, N};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = clickGraph_model_namespace::clickGraph_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return clickGraph_model_namespace::profiles__;
}

#endif


