timeout 2000s webppl baselines/webppl/or_5/or_5.wppl --require webppl-timeit -- --s $((2**24)) --m MCMC >> baselines/webppl/or_5/output_MCMC_24_new.txt
timeout 2000s webppl baselines/webppl/or_10/or_10.wppl --require webppl-timeit -- --s $((2**24)) --m MCMC >> baselines/webppl/or_10/output_MCMC_24_new.txt
timeout 2000s webppl baselines/webppl/or_15/or_15.wppl --require webppl-timeit -- --s $((2**24)) --m MCMC >> baselines/webppl/or_15/output_MCMC_24_new.txt
timeout 2000s webppl baselines/webppl/or_20/or_20.wppl --require webppl-timeit -- --s $((2**24)) --m MCMC >> baselines/webppl/or_20/output_MCMC_24_new.txt
timeout 2000s webppl baselines/webppl/or_25/or_25.wppl --require webppl-timeit -- --s $((2**23)) --m MCMC >> baselines/webppl/or_25/output_MCMC_23_new.txt
timeout 2000s webppl baselines/webppl/or_30/or_30.wppl --require webppl-timeit -- --s $((2**23)) --m MCMC >> baselines/webppl/or_30/output_MCMC_23_new.txt
timeout 2000s webppl baselines/webppl/or_35/or_35.wppl --require webppl-timeit -- --s $((2**23)) --m MCMC >> baselines/webppl/or_35/output_MCMC_23_new.txt
timeout 2000s webppl baselines/webppl/or_40/or_40.wppl --require webppl-timeit -- --s $((2**23)) --m MCMC >> baselines/webppl/or_40/output_MCMC_23_new.txt
timeout 2000s webppl baselines/webppl/or_45/or_45.wppl --require webppl-timeit -- --s $((2**23)) --m MCMC >> baselines/webppl/or_45/output_MCMC_23_new.txt
timeout 2000s webppl baselines/webppl/or_50/or_50.wppl --require webppl-timeit -- --s $((2**23)) --m MCMC >> baselines/webppl/or_50/output_MCMC_23_new.txt