
// Code generated by stanc v2.28.1
#include <stan/model/model_header.hpp>
namespace clinicalTrial2_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 31> locations_array__ = 
{" (found before start of program)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 9, column 2 to column 43)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 10, column 2 to column 39)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 13, column 2 to column 43)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 15, column 2 to column 15)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 16, column 2 to column 24)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 18, column 3 to column 68)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 26, column 2 to column 32)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 28, column 12 to column 83)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 29, column 12 to column 83)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 27, column 24 to line 30, column 9)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 27, column 9 to line 30, column 9)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 25, column 13 to line 32, column 7)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 20, column 16 to column 42)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 22, column 12 to column 83)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 23, column 12 to column 83)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 21, column 24 to line 24, column 3)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 21, column 9 to line 24, column 3)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 19, column 32 to line 25, column 8)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 19, column 7 to line 32, column 7)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 17, column 31 to line 33, column 5)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 17, column 2 to line 33, column 5)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 36, column 2 to column 32)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 37, column 2 to column 28)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 39, column 2 to column 40)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 2, column 2 to column 8)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 3, column 19 to column 20)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 3, column 2 to column 22)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 4, column 2 to column 18)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 5, column 19 to column 20)",
 " (in 'benchmarks/clinicalTrial2/clinicalTrial2.stan', line 5, column 2 to column 22)"};



class clinicalTrial2_model final : public model_base_crtp<clinicalTrial2_model> {

 private:
  int N;
  std::vector<int> controlGroup;
  int isEffective;
  std::vector<int> treatedGroup; 
  
 
 public:
  ~clinicalTrial2_model() { }
  
  inline std::string model_name() const final { return "clinicalTrial2_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.28.1", "stancflags = "};
  }
  
  
  clinicalTrial2_model(stan::io::var_context& context__,
                       unsigned int random_seed__ = 0,
                       std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "clinicalTrial2_model_namespace::clinicalTrial2_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 25;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 25;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 26;
      validate_non_negative_index("controlGroup", "N", N);
      current_statement__ = 27;
      context__.validate_dims("data initialization","controlGroup","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      controlGroup = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 27;
      controlGroup = context__.vals_i("controlGroup");
      current_statement__ = 28;
      context__.validate_dims("data initialization","isEffective","int",
           std::vector<size_t>{});
      isEffective = std::numeric_limits<int>::min();
      
      current_statement__ = 28;
      isEffective = context__.vals_i("isEffective")[(1 - 1)];
      current_statement__ = 29;
      validate_non_negative_index("treatedGroup", "N", N);
      current_statement__ = 30;
      context__.validate_dims("data initialization","treatedGroup","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      treatedGroup = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 30;
      treatedGroup = context__.vals_i("treatedGroup");
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "clinicalTrial2_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ probIfTreated;
      probIfTreated = DUMMY_VAR__;
      
      current_statement__ = 1;
      probIfTreated = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
                        0, 1, lp__);
      local_scalar_t__ probextra;
      probextra = DUMMY_VAR__;
      
      current_statement__ = 2;
      probextra = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
                    0, 1, lp__);
      local_scalar_t__ probIfControl;
      probIfControl = DUMMY_VAR__;
      
      Eigen::Matrix<local_scalar_t__, -1, 1> lp;
      lp = Eigen::Matrix<local_scalar_t__, -1, 1>(2);
      stan::math::fill(lp, DUMMY_VAR__);
      
      current_statement__ = 5;
      assign(lp, rep_vector(0, 2), "assigning variable lp");
      current_statement__ = 21;
      for (int isEffective_val = 1; isEffective_val <= 2; ++isEffective_val) {
        current_statement__ = 6;
        assign(lp,
          (rvalue(lp, "lp", index_uni(isEffective_val)) +
            bernoulli_lpmf<false>((isEffective_val - 1), 0.5)),
          "assigning variable lp", index_uni(isEffective_val));
        current_statement__ = 19;
        if (logical_gt(isEffective_val, 1)) {
          current_statement__ = 13;
          probIfControl = probextra;
          current_statement__ = 17;
          for (int n = 1; n <= N; ++n) {
            current_statement__ = 14;
            assign(lp,
              (rvalue(lp, "lp", index_uni(isEffective_val)) +
                bernoulli_lpmf<false>(
                  rvalue(controlGroup, "controlGroup", index_uni(n)),
                  probIfControl)),
              "assigning variable lp", index_uni(isEffective_val));
            current_statement__ = 15;
            assign(lp,
              (rvalue(lp, "lp", index_uni(isEffective_val)) +
                bernoulli_lpmf<false>(
                  rvalue(treatedGroup, "treatedGroup", index_uni(n)),
                  probIfTreated)),
              "assigning variable lp", index_uni(isEffective_val));
          }
        } else {
          current_statement__ = 7;
          probIfControl = probIfTreated;
          current_statement__ = 11;
          for (int n = 1; n <= N; ++n) {
            current_statement__ = 8;
            assign(lp,
              (rvalue(lp, "lp", index_uni(isEffective_val)) +
                bernoulli_lpmf<false>(
                  rvalue(controlGroup, "controlGroup", index_uni(n)),
                  probIfControl)),
              "assigning variable lp", index_uni(isEffective_val));
            current_statement__ = 9;
            assign(lp,
              (rvalue(lp, "lp", index_uni(isEffective_val)) +
                bernoulli_lpmf<false>(
                  rvalue(treatedGroup, "treatedGroup", index_uni(n)),
                  probIfTreated)),
              "assigning variable lp", index_uni(isEffective_val));
          }
        }
      }
      current_statement__ = 3;
      check_greater_or_equal(function__, "probIfControl", probIfControl, 0);
      current_statement__ = 3;
      check_less_or_equal(function__, "probIfControl", probIfControl, 1);
      {
        current_statement__ = 22;
        lp_accum__.add(uniform_lpdf<propto__>(probIfTreated, 0, 1));
        current_statement__ = 23;
        lp_accum__.add(uniform_lpdf<propto__>(probextra, 0, 1));
        current_statement__ = 24;
        lp_accum__.add(
          (isEffective ? rvalue(lp, "lp", index_uni(2)) :
             rvalue(lp, "lp", index_uni(1))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "clinicalTrial2_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double probIfTreated;
      probIfTreated = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      probIfTreated = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
                        0, 1, lp__);
      double probextra;
      probextra = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      probextra = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(
                    0, 1, lp__);
      double probIfControl;
      probIfControl = std::numeric_limits<double>::quiet_NaN();
      
      Eigen::Matrix<double, -1, 1> lp;
      lp = Eigen::Matrix<double, -1, 1>(2);
      stan::math::fill(lp, std::numeric_limits<double>::quiet_NaN());
      
      out__.write(probIfTreated);
      out__.write(probextra);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 5;
      assign(lp, rep_vector(0, 2), "assigning variable lp");
      current_statement__ = 21;
      for (int isEffective_val = 1; isEffective_val <= 2; ++isEffective_val) {
        current_statement__ = 6;
        assign(lp,
          (rvalue(lp, "lp", index_uni(isEffective_val)) +
            bernoulli_lpmf<false>((isEffective_val - 1), 0.5)),
          "assigning variable lp", index_uni(isEffective_val));
        current_statement__ = 19;
        if (logical_gt(isEffective_val, 1)) {
          current_statement__ = 13;
          probIfControl = probextra;
          current_statement__ = 17;
          for (int n = 1; n <= N; ++n) {
            current_statement__ = 14;
            assign(lp,
              (rvalue(lp, "lp", index_uni(isEffective_val)) +
                bernoulli_lpmf<false>(
                  rvalue(controlGroup, "controlGroup", index_uni(n)),
                  probIfControl)),
              "assigning variable lp", index_uni(isEffective_val));
            current_statement__ = 15;
            assign(lp,
              (rvalue(lp, "lp", index_uni(isEffective_val)) +
                bernoulli_lpmf<false>(
                  rvalue(treatedGroup, "treatedGroup", index_uni(n)),
                  probIfTreated)),
              "assigning variable lp", index_uni(isEffective_val));
          }
        } else {
          current_statement__ = 7;
          probIfControl = probIfTreated;
          current_statement__ = 11;
          for (int n = 1; n <= N; ++n) {
            current_statement__ = 8;
            assign(lp,
              (rvalue(lp, "lp", index_uni(isEffective_val)) +
                bernoulli_lpmf<false>(
                  rvalue(controlGroup, "controlGroup", index_uni(n)),
                  probIfControl)),
              "assigning variable lp", index_uni(isEffective_val));
            current_statement__ = 9;
            assign(lp,
              (rvalue(lp, "lp", index_uni(isEffective_val)) +
                bernoulli_lpmf<false>(
                  rvalue(treatedGroup, "treatedGroup", index_uni(n)),
                  probIfTreated)),
              "assigning variable lp", index_uni(isEffective_val));
          }
        }
      }
      current_statement__ = 3;
      check_greater_or_equal(function__, "probIfControl", probIfControl, 0);
      current_statement__ = 3;
      check_less_or_equal(function__, "probIfControl", probIfControl, 1);
      if (emit_transformed_parameters__) {
        out__.write(probIfControl);
        out__.write(lp);
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      local_scalar_t__ probIfTreated;
      probIfTreated = DUMMY_VAR__;
      
      probIfTreated = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, probIfTreated);
      local_scalar_t__ probextra;
      probextra = DUMMY_VAR__;
      
      probextra = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, probextra);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"probIfTreated", "probextra",
      "probIfControl", "lp"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(2)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "probIfTreated");
    param_names__.emplace_back(std::string() + "probextra");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "probIfControl");
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "lp" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "probIfTreated");
    param_names__.emplace_back(std::string() + "probextra");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "probIfControl");
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "lp" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"probIfTreated\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"probextra\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"probIfControl\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"lp\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"probIfTreated\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"probextra\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"probIfControl\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"lp\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (1 + 1);
      const size_t num_transformed = (1 + 2);
      const size_t num_gen_quantities = 0;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (1 + 1);
      const size_t num_transformed = (1 + 2);
      const size_t num_gen_quantities = 0;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 2> names__{"probIfTreated",
      "probextra"};
      const std::array<Eigen::Index, 2> constrain_param_sizes__{1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = clinicalTrial2_model_namespace::clinicalTrial2_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return clinicalTrial2_model_namespace::profiles__;
}

#endif


